# Site settings
name: j的博客
email: 184263567@qq.com
author: j
url: http://zangji6253.github.io
resume_site: http://http://zangji6253.github.io/me/
github: https://github.com/zangji6253/
baseurl: ""  #根目录
description: 123
motto: 456
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 789
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: zangji6253
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : j
